import { Station } from './types';

export const INITIAL_STATIONS: Station[] = [
  // ==========================================
  // KIGALI, RWANDA EV CHARGING NETWORK
  // ==========================================
  {
    id: 'st-kigali-01',
    name: 'Kigali Convention Centre Fast Hub',
    address: 'KG 2 Roundabout, Kimihurura, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9536,
    longitude: 30.0924,
    operator_name: 'Rwanda Energy Group (REG) & Radisson',
    status: 'ACTIVE',
    pricing_info: '280 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['RESTROOM', 'COFFEE', 'RESTAURANT', 'WIFI', 'TWENTY_FOUR_SEVEN', 'HOTEL'],
    user_id: 'usr-admin-01',
    user_email: 'admin@evchargers.rw',
    connectors: [
      {
        id: 'c-kgl-01-1',
        station_id: 'st-kigali-01',
        connector_type: 'CCS_2',
        power_kw: 150,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-01-2',
        station_id: 'st-kigali-01',
        connector_type: 'GB_T',
        power_kw: 120,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-01-3',
        station_id: 'st-kigali-01',
        connector_type: 'TYPE_2',
        power_kw: 22,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'AC',
      },
    ],
    notes: 'Located in the main VIP parking lot with 24/7 security. Dedicated EV bays.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-02',
    name: 'Kigali Heights EV Charging Plaza',
    address: 'KG 7 Ave, Boulevard de l’Umuganda, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9528,
    longitude: 30.0945,
    operator_name: 'Ampersand & Kigali Heights',
    status: 'ACTIVE',
    pricing_info: '300 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['SHOPPING', 'COFFEE', 'RESTROOM', 'RESTAURANT', 'WIFI'],
    user_id: 'usr-operator-02',
    user_email: 'operator@kigalihub.rw',
    connectors: [
      {
        id: 'c-kgl-02-1',
        station_id: 'st-kigali-02',
        connector_type: 'CCS_2',
        power_kw: 100,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-02-2',
        station_id: 'st-kigali-02',
        connector_type: 'GB_T',
        power_kw: 100,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-02-3',
        station_id: 'st-kigali-02',
        connector_type: 'TYPE_2',
        power_kw: 22,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'AC',
      },
    ],
    notes: 'Ground level parking entrance behind Simba Supermarket. Supports Chinese & European EV imports.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-03',
    name: 'BK Arena High-Power Charging Station',
    address: 'KG 17 Ave, Remera, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9525,
    longitude: 30.1130,
    operator_name: 'BK Arena Power',
    status: 'ACTIVE',
    pricing_info: '250 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['RESTROOM', 'TWENTY_FOUR_SEVEN', 'ACCESSIBLE', 'COFFEE'],
    user_id: 'usr-admin-01',
    user_email: 'admin@evchargers.rw',
    connectors: [
      {
        id: 'c-kgl-03-1',
        station_id: 'st-kigali-03',
        connector_type: 'CCS_2',
        power_kw: 250,
        quantity: 6,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-03-2',
        station_id: 'st-kigali-03',
        connector_type: 'GB_T',
        power_kw: 150,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-03-3',
        station_id: 'st-kigali-03',
        connector_type: 'NACS',
        power_kw: 150,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
    ],
    notes: 'Ultra-fast chargers located near Gate 2. Open 24/7 including event days.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-04',
    name: 'Norrsken House Kigali Green Hub',
    address: 'KN 78 St, Kiyovu / Downtown, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9560,
    longitude: 30.0620,
    operator_name: 'Norrsken East Africa',
    status: 'ACTIVE',
    pricing_info: 'Free for campus visitors & co-workers',
    is_free: true,
    access_type: 'PUBLIC',
    amenities: ['COFFEE', 'WIFI', 'RESTROOM', 'ACCESSIBLE'],
    user_id: 'usr-operator-02',
    user_email: 'operator@kigalihub.rw',
    connectors: [
      {
        id: 'c-kgl-04-1',
        station_id: 'st-kigali-04',
        connector_type: 'TYPE_2',
        power_kw: 22,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'AC',
      },
      {
        id: 'c-kgl-04-2',
        station_id: 'st-kigali-04',
        connector_type: 'GB_T',
        power_kw: 60,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
    ],
    notes: 'Solar-powered charging bays situated at the main campus entrance.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-05',
    name: 'Kigali International Airport (KIA) EV Hub',
    address: 'Airport Rd, Kanombe, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9686,
    longitude: 30.1340,
    operator_name: 'Rwanda Airports Company (RAC)',
    status: 'ACTIVE',
    pricing_info: '320 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['RESTROOM', 'COFFEE', 'TWENTY_FOUR_SEVEN', 'WIFI', 'RESTAURANT'],
    user_id: 'usr-admin-01',
    user_email: 'admin@evchargers.rw',
    connectors: [
      {
        id: 'c-kgl-05-1',
        station_id: 'st-kigali-05',
        connector_type: 'CCS_2',
        power_kw: 150,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-05-2',
        station_id: 'st-kigali-05',
        connector_type: 'GB_T',
        power_kw: 120,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-05-3',
        station_id: 'st-kigali-05',
        connector_type: 'CHADEMO',
        power_kw: 50,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
    ],
    notes: 'Located in the short-stay passenger pickup parking area.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-06',
    name: 'Nyabugogo Transport Hub Fast Charger',
    address: 'KN 1 Rd, Nyabugogo, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9380,
    longitude: 30.0450,
    operator_name: 'Spiro / BasiGo',
    status: 'MAINTENANCE',
    pricing_info: '220 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['RESTROOM', 'TWENTY_FOUR_SEVEN'],
    user_id: 'usr-operator-02',
    user_email: 'operator@kigalihub.rw',
    connectors: [
      {
        id: 'c-kgl-06-1',
        station_id: 'st-kigali-06',
        connector_type: 'GB_T',
        power_kw: 160,
        quantity: 4,
        status: 'FAULTED',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-06-2',
        station_id: 'st-kigali-06',
        connector_type: 'CCS_2',
        power_kw: 120,
        quantity: 2,
        status: 'FAULTED',
        current_type: 'DC',
      },
    ],
    notes: 'High-power GB/T bus charging station. Transformer upgrade in progress.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-07',
    name: 'M.Peace Plaza Downtown Station',
    address: 'KN 4 Ave, Nyarugenge, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9485,
    longitude: 30.0605,
    operator_name: 'Downtown EV Corp',
    status: 'ACTIVE',
    pricing_info: '290 RWF / kWh',
    is_free: false,
    access_type: 'PUBLIC',
    amenities: ['SHOPPING', 'COFFEE', 'RESTROOM', 'RESTAURANT', 'WIFI'],
    user_id: 'usr-admin-01',
    user_email: 'admin@evchargers.rw',
    connectors: [
      {
        id: 'c-kgl-07-1',
        station_id: 'st-kigali-07',
        connector_type: 'GB_T',
        power_kw: 100,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-07-2',
        station_id: 'st-kigali-07',
        connector_type: 'CCS_2',
        power_kw: 100,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-07-3',
        station_id: 'st-kigali-07',
        connector_type: 'TYPE_2',
        power_kw: 22,
        quantity: 4,
        status: 'AVAILABLE',
        current_type: 'AC',
      },
    ],
    notes: 'Underground parking level -1.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'st-kigali-08',
    name: 'Gishushu Simba Rapid EV Station',
    address: 'KG 8 Ave, Gishushu, Kigali, Rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    latitude: -1.9470,
    longitude: 30.0880,
    operator_name: 'Simba Supermarket EV',
    status: 'ACTIVE',
    pricing_info: 'Free for shoppers spending > 20,000 RWF',
    is_free: true,
    access_type: 'CUSTOMERS_ONLY',
    amenities: ['SHOPPING', 'COFFEE', 'RESTROOM'],
    user_id: 'usr-operator-02',
    user_email: 'operator@kigalihub.rw',
    connectors: [
      {
        id: 'c-kgl-08-1',
        station_id: 'st-kigali-08',
        connector_type: 'GB_T',
        power_kw: 60,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-08-2',
        station_id: 'st-kigali-08',
        connector_type: 'CCS_2',
        power_kw: 50,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'DC',
      },
      {
        id: 'c-kgl-08-3',
        station_id: 'st-kigali-08',
        connector_type: 'TYPE_2',
        power_kw: 22,
        quantity: 2,
        status: 'AVAILABLE',
        current_type: 'AC',
      },
    ],
    notes: 'Validation voucher available at cashier checkout.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
